name: YOLO Commit

on:
  schedule:
    - cron: '0 0 * * *'  # This cron expression schedules the workflow to run at midnight UTC
  workflow_dispatch:

jobs:
  yolo_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make a YOLO commit
      run: |
        echo "YOLO commit at midnight" > yolo.txt
        git config --global user.email "kimutaij192@gmail.com"
        git config --global user.name "yunghavy"
        git add yolo.txt
        git commit -m "YOLO commit at midnight"
        git push
